Entry activity layout design
saeedntt/HydrationReminder pull request #11
Opened 2020-11-21 13:10 UTC by nrazavi70

2020-11-21 14:03 UTC, saeedntt requested changes

2020-11-21 14:03 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +        val sharedPrefEditor = sharedPref.edit()
Create a class for managing shared preferences. This class will be responsible for saving to and reading from shared preferences.

2020-11-21 14:03 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +                findViewById<RadioButton>(notificationSoundGroup.checkedRadioButtonId)
If you are not executing the same command on all of the items no point in putting them inside an array.

2020-11-21 14:03 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +        entryPageSubmitButton.setOnClickListener {
On click listeners are events. Events are the responsibility of the viewModel. Create a class with a proper name that will handle the events of the view and is responsible for view actions. Then create an instance of that class inside the activity. Then when you find the view inside activity, you pass it to the viewmodel. Then view model will take care of the actions related to that item.

2020-11-21 14:03 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +                    wakeUpTimeError.text = "Please enter a valid time."
Use the TextInputLayout with TextInputEditText then you dont need to create an error text manually.

2020-11-21 14:03 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +                    sleepTimeError.text = "Please enter a valid time."
Same as above about TextInputLayout.

2020-11-21 14:03 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +                        sharedPrefEditor.putString(key.toString(), this[key].text.toString())
Create proper keys. Indexes are not keys. You need to create a unique key for values that you want to add in shared preferences. Create a class that keeps your keys as static constants then you can use them in your view model to save meaningful values in shared preferences.

2020-11-21 14:08 UTC, nrazavi70 commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +                findViewById<RadioButton>(notificationSoundGroup.checkedRadioButtonId)
I am executing the putString method of shared preferences on all of them. Is that enough reason to put them all in an array?

2020-11-21 14:13 UTC, saeedntt commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +                    wakeUpTimeError.text = "Please enter a valid time."
https://material.io/develop/android/components/text-fields

2020-11-22 05:32 UTC, nrazavi70 commented on app/src/main/java/com/reminder/hydration/EntryActivity.kt
> +        val sharedPrefEditor = sharedPref.edit()
I tried creating a class with these variables for start but getSharedPreferences is "Unresolved Reference". I can't seem to be finding a way around it.
Also it seems redundant cause getSharedPreferences on its own is a class to handle shared preferences. Would you mind elaborating on what the purpose of this class is?

2020-12-26 14:36 UTC, closed without merging